-- Phase 23: MASA Engrams Persistence (Optional - Memory Layer)
-- Created: 2026-01-24
-- Purpose: Store successful patterns (Engrams) for Layer 0 memory across sessions

-- =============================================
-- TABLE: masa_engrams
-- =============================================
CREATE TABLE IF NOT EXISTS public.masa_engrams (
  id TEXT PRIMARY KEY, -- UUID generated by MasaMemory
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  
  -- Engram Content
  thesis TEXT NOT NULL,
  mechanism TEXT NOT NULL,
  domain TEXT NOT NULL CHECK (domain IN ('Physics', 'Chemistry', 'Biology', 'Computer Science', 'General')),
  lens TEXT NOT NULL,
  
  -- Performance Metrics
  validity_score INTEGER NOT NULL CHECK (validity_score >= 0 AND validity_score <= 100),
  
  -- Timestamps
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  
  -- Index for fast retrieval
  CONSTRAINT engrams_user_domain_idx UNIQUE (user_id, domain, id)
);

-- =============================================
-- RLS POLICIES
-- =============================================
ALTER TABLE public.masa_engrams ENABLE ROW LEVEL SECURITY;

-- Users can only read their own engrams
CREATE POLICY "Users can read own engrams"
  ON public.masa_engrams
  FOR SELECT
  USING (auth.uid() = user_id);

-- Users can insert their own engrams
CREATE POLICY "Users can insert own engrams"
  ON public.masa_engrams
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- Service role has full access
CREATE POLICY "Service role has full access to engrams"
  ON public.masa_engrams
  FOR ALL
  USING (auth.jwt()->>'role' = 'service_role');

-- =============================================
-- INDEXES
-- =============================================
CREATE INDEX IF NOT EXISTS idx_masa_engrams_user_id 
  ON public.masa_engrams(user_id);

CREATE INDEX IF NOT EXISTS idx_masa_engrams_domain 
  ON public.masa_engrams(domain);

CREATE INDEX IF NOT EXISTS idx_masa_engrams_created_at 
  ON public.masa_engrams(created_at DESC);

-- GIN index for text search on thesis/mechanism
CREATE INDEX IF NOT EXISTS idx_masa_engrams_thesis_gin 
  ON public.masa_engrams USING GIN (to_tsvector('english', thesis || ' ' || mechanism));
